### ISSUE TITLE
Various (S7)

### ISSUE THREAD

**Issue by oliviercailloux** [dramanebamba/pole_info#14]
Pom incorrect (cf échantillons)
Voir warnings et erreurs Eclipse en mode strict (cf Best practices cours)
Pages pas dans WEB-INF
JPA ?
Ne pas utiliser Vector (préférer List) sauf si justifié
Méthodes convention de nommage (cf Best practices), expl CreationContenu
Coder en anglais
Éviter setAttribute globaux, privilégier CDI & JSF.

**Comment by dramanebamba** [comment]
pom.xml corrigé sur la branche issue13 : à valider
Les erreurs ont corrigée, les warnings ne sont pas importants
Où doit-on placer les pages?
JPA a été implémenté pour dans les classes CoursService et PostCours de l'issue 13.
Ok pour Vector
Convention de nommage : je ne comprends pas à quoi cela fait référence
Coder en anglais : Ok
Privilégier CDI et JSF : Ok
